/**
 * Data Katalog Proyek Portofolio
 * Menyimpan seluruh metadata proyek terverifikasi untuk rendering kartu, modal detail spesifikasi, dan arsip repositori.
 */

const projectsData = [
  {
    id: 0,
    title: "Tatagih",
    category: "Financial SaaS & AI",
    categoryType: "web",
    role: "Lead Fullstack & AI Systems Developer",
    type: "Smart Subscription Manager & AI Financial Assistant",
    status: "Full-Stack Showcase (2024)",
    period: "2024",
    image: "assets/tatagih.webp",
    description: "Platform manajemen langganan dan asisten finansial bertenaga Google Gemini untuk sentralisasi tagihan, deteksi vampire spending, dan otomasi pengingat Telegram.",
    problem: "Di era digital, hampir setiap orang memiliki beragam layanan berlangganan (streaming, produktivitas, cloud storage, AI tools). Masalah yang sering terjadi: pencatatan tercecer tanpa tempat terpusat, tagihan terlupakan hingga memicu auto-renewal tanpa disadari, kebocoran dana (vampire spending) akibat langganan tumpang tindih (overlapping), serta kesulitan membagi tagihan akun keluarga (Family Plan) dan memverifikasi bukti bayar secara manual.",
    solution: "Tatagih mentransformasi manajemen pengeluaran digital melalui ekosistem terpadu Laravel 13 & MySQL: sentralisasi langganan dengan siklus fleksibel, Tata Asisten AI bertenaga Google Gemini untuk Financial Health Score (0-100) dan rekomendasi efisiensi, algoritma deteksi overlapping/vampire spending, modul patungan terintegrasi upload & verifikasi bukti transfer, serta proactive reminder otomatis H-3 & H-1 via Telegram Bot berbasis Laravel Scheduler & Queue.",
    stats: [
      { label: "Tata Asisten AI", val: "Financial Health Score (Gemini)" },
      { label: "Deteksi Kebocoran", val: "Overlapping & Vampire Spending" },
      { label: "Patungan / Split-Bill", val: "Auto-Split & Verifikasi Bukti" },
      { label: "Reminder Engine", val: "Telegram Bot (Scheduler & Queue)" },
    ],
    features: [
      {
        title: "Manajemen Subscription & Ekspor CSV",
        desc: "Tambah, edit, filter kategori, auto-renewal toggle, dan unduh rekapan CSV pengeluaran berkala.",
      },
      {
        title: "Financial Dashboard & Calendar (Chart.js)",
        desc: "Estimasi biaya bulanan/tahunan, kalender tagihan jatuh tempo, dan visualisasi tren 6 bulan.",
      },
      {
        title: "Tata Asisten & Financial Health Score",
        desc: "Evaluasi kebiasaan berlangganan dengan skor 0-100 dan saran penghematan biaya bertenaga Google Gemini.",
      },
      {
        title: "Tata AI Chat Interaktif",
        desc: "Chat asisten finansial kontekstual multi-sesi dengan fallback engine lokal jika API AI offline.",
      },
      {
        title: "Pendeteksi Overlapping & Vampire Spending",
        desc: "Kalkulasi penghematan dari layanan digital dengan fungsi yang saling tumpang tindih.",
      },
      {
        title: "Perbandingan Paket Subscription",
        desc: "Komparasi fitur dan harga paket sebelum pengguna memutuskan untuk berlangganan.",
      },
      {
        title: "Smart Templates",
        desc: "Preset 1-klik untuk layanan populer (Netflix, Spotify, ChatGPT Plus, YouTube, Google One, dll.).",
      },
      {
        title: "Sistem Patungan & Upload Bukti",
        desc: "Pembagian tagihan grup keluarga (Family Plan) secara adil dengan verifikasi struk transfer bayar.",
      },
      {
        title: "Sistem User Tag Unik",
        desc: "Format tag unik (@krisna#2024) untuk berteman dan membuat grup patungan langganan bersama.",
      },
      {
        title: "Proactive Telegram Bot Alert",
        desc: "Notifikasi reminder H-3 dan H-1 sebelum tanggal jatuh tempo berbasis Laravel Scheduler & Queue.",
      },
      {
        title: "Admin Dashboard Operasional",
        desc: "Pemantauan metrik pengguna, volume langganan aktif, dan laju pertumbuhan ekosistem sistem.",
      },
    ],
    techStack: ["PHP", "Laravel 13", "Laravel Blade", "Tailwind CSS", "Vite", "JavaScript", "MySQL", "Chart.js", "Google Gemini API", "Telegram Bot API", "Laravel Scheduler & Queue", "PHPUnit"],
    impact: "Mengeliminasi kebocoran dana langganan digital, mempermudah koordinasi patungan keluarga, dan mengotomatisasi pengawasan jatuh tempo tagihan secara proaktif.",
    demoUrl: "",
    demoText: "Lihat Demo",
    demoIcon: "fa-arrow-up-right-from-square",
    repoUrl: "https://github.com/ANTARTICA1/Subscription-Guard",
    repoText: "Lihat di GitHub",
  },
  {
    id: 1,
    title: "SIGAP",
    category: "Mobile Security",
    categoryType: "cyber",
    role: "Mobile Security & Flutter Developer",
    type: "Device Anti-Theft & Alarm Application",
    status: "Production Prototype (2024)",
    period: "2024",
    image: "assets/sigap.svg",
    description: "Aplikasi keamanan mobile cerdas untuk melindungi perangkat saat ditinggalkan di ruang publik dengan siklus Detect → Alert → Lock → Record → Review.",
    problem: "Saat smartphone ditinggalkan di tempat umum (meja kafe, ruang rapat, perpustakaan, atau saat mengisi daya), perangkat sangat rentan diambil atau dicabut chargernya oleh tangan jahil tanpa sepengetahuan pemilik.",
    solution: "SIGAP menerapkan siklus pengamanan terpadu berbasis sensor hardware: Detect (memantau stream akselerometer sumbu XYZ dan status kabel charger), Alert (sirine looping, getaran darurat, Volume Watchdog 100%), Lock (layar darurat immersiveSticky terkunci rapat dengan PIN lokal), Record (kamera depan diam-diam memotret wajah pelaku dan mencatat GPS darurat), dan Review (menyimpan riwayat insiden lokal untuk inspeksi forensik).",
    stats: [
      { label: "Motion Threshold", val: "Δ >= 2.0 (Stream Akselerometer XYZ)" },
      { label: "Hardware Sensor", val: "Akselerometer & Deteksi Charger" },
      { label: "Respons Darurat", val: "100% Volume Watchdog + Foto + GPS" },
      { label: "Penundaan Siaga", val: "Countdown 5 Detik Bidang Datar" },
    ],
    features: [
      {
        title: "Motion Detection",
        desc: "Pemicuan alarm seketika jika HP diangkat atau digeser melebihi ambang batas toleransi (Δ >= 2.0).",
      },
      {
        title: "Charger Removal Detection & Alarm",
        desc: "Alarm seketika saat kabel charger dilepas paksa dalam kondisi sistem aktif (armed).",
      },
      {
        title: "100% Volume Watchdog & Layar PIN",
        desc: "Sirine berbunyi pada volume maksimal 100% anti-batal dengan penguncian layar darurat berbasis PIN lokal.",
      },
      {
        title: "Intruder Selfie Kamera Depan & Snapshot GPS",
        desc: "Potret otomatis wajah pelaku menggunakan kamera depan dan perekaman koordinat GPS darurat saat alarm terpicu.",
      },
      {
        title: "Countdown Penempatan",
        desc: "Jeda 5 detik bagi pengguna untuk memposisikan HP di bidang datar sebelum sensor aktif.",
      },
      {
        title: "Vibration Alert Pattern",
        desc: "Pola getaran darurat berulang untuk menarik perhatian massa di sekitar lokasi insiden.",
      },
      {
        title: "Log Riwayat Insiden",
        desc: "Menyimpan hingga 50 catatan insiden keamanan terakhir secara lokal untuk inspeksi pemilik.",
      },
      {
        title: "Emergency Contact Launcher",
        desc: "Pintasan cepat ke WhatsApp atau SMS nomor kerabat untuk meminta pertolongan darurat.",
      },
    ],
    techStack: ["Flutter", "Dart", "Provider", "Sensors Plus (Accelerometer)", "Battery Plus", "Camera API", "Geolocator", "SharedPreferences", "Volume Controller", "Wakelock Plus", "Flutter Ringtone Player"],
    impact: "Mengamankan perangkat dari pencurian fisik di ruang publik secara instan dengan bukti foto pelaku dan koordinat GPS.",
    demoUrl: "",
    demoText: "Lihat Demo",
    demoIcon: "fa-arrow-up-right-from-square",
    repoUrl: "https://github.com/ANTARTICA1",
    repoText: "Lihat di GitHub",
  },
  {
    id: 2,
    title: "Temuin",
    category: "Lost & Found Platform",
    categoryType: "cyber",
    role: "Fullstack Mobile & Security API Developer",
    type: "QR Lost & Found Community Ecosystem",
    status: "Production Prototype (2024)",
    period: "2024",
    image: "assets/temuin.webp",
    description: "Platform pelacak dan pengembalian barang hilang berbasis stiker QR Code unik dan snapshot GPS dengan perlindungan privasi pemilik serta Midtrans payment gateway.",
    problem: "Barang berharga (kunci, dompet, tas, dokumen, laptop) yang tertinggal di ruang publik sulit kembali karena penemu tidak tahu siapa pemiliknya. Di sisi lain, memajang nomor telepon langsung di barang berisiko melanggar privasi dan rawan penipuan.",
    solution: "Temuin menghubungkan pemilik dan penemu melalui rantai: Pemilik Barang → QR Code → Penemu → Laporan → Lokasi GPS → Notifikasi In-App → Pengambilan. Penemu cukup memindai QR Code untuk mengisi formulir laporan dengan foto bukti dan titik GPS tanpa mengetahui nomor pribadi pemilik, diverifikasi dengan custom Bearer token HMAC-SHA256.",
    stats: [
      { label: "Siklus Status", val: "Safe → Lost → Found → Claimed" },
      { label: "Metode Verifikasi", val: "GPS Snapshot + Foto Bukti Kamera" },
      { label: "Keamanan Server", val: "Custom Token HMAC-SHA256" },
      { label: "Monetisasi", val: "Boost Listing via Midtrans Snap" },
    ],
    features: [
      {
        title: "QR Code Digital Identity",
        desc: "Menghubungkan fisik barang ke sistem digital tanpa mengekspos nomor HP atau data pribadi pemilik.",
      },
      {
        title: "Scanner Kamera Instan",
        desc: "Modul pemindai kode QR cepat berbasis kamera perangkat menggunakan mobile_scanner.",
      },
      {
        title: "GPS Snapshot Lokasi Temuan",
        desc: "Merekam koordinat latitude/longitude saat laporan dibuat untuk memandu pemilik ke lokasi barang.",
      },
      {
        title: "Dokumentasi Foto Bukti",
        desc: "Melampirkan foto kondisi fisik barang saat ditemukan untuk verifikasi visual langsung.",
      },
      {
        title: "Siklus Status Barang Terstruktur",
        desc: "Memantau tahapan barang dari aman (Safe), hilang (Lost), ditemukan (Found), hingga selesai diklaim (Claimed).",
      },
      {
        title: "Validasi Anti Self-Claim",
        desc: "Logika server yang melarang keras pemilik melaporkan klaim penemuan barang miliknya sendiri.",
      },
      {
        title: "Notifikasi In-App Real-Time",
        desc: "Pemilik langsung menerima notifikasi peringatan begitu ada laporan penemuan baru terkait barangnya.",
      },
      {
        title: "Monetisasi Boost Postingan",
        desc: "Opsi menaikkan barang hilang ke daftar prioritas (Featured) via Midtrans Snap (Signature SHA-512).",
      },
      {
        title: "Web Admin Dashboard",
        desc: "Pusat pemantauan inventaris barang, audit laporan temuan, dan manajemen akun pengguna.",
      },
    ],
    techStack: ["Flutter", "Dart", "Material 3", "PHP Native", "PDO", "MySQL", "Midtrans Snap", "qr_flutter", "mobile_scanner", "geolocator", "image_picker", "Custom HMAC-SHA256 Bearer Token"],
    impact: "Memulihkan barang berharga yang hilang secara cepat, aman, dan menjaga kerahasiaan identitas pemilik dari potensi penipuan.",
    demoUrl: "",
    demoText: "Lihat Demo",
    demoIcon: "fa-arrow-up-right-from-square",
    repoUrl: "https://github.com/ANTARTICA1/temuin-flutter",
    repoText: "Lihat di GitHub",
  },
  {
    id: 3,
    title: "Lintas",
    category: "Cross-Device Systems",
    categoryType: "tools",
    role: "Cross-Platform Systems & Networking Developer",
    type: "Zero-Cloud Cross-Device Productivity Ecosystem",
    status: "Production Showcase (2024)",
    period: "2024",
    image: "assets/lintas.svg",
    description: "Ekosistem produktivitas lintas perangkat yang menghubungkan Android dan Windows secara lokal (Zero Cloud) dengan kontrol latensi sangat rendah (<12ms) dan auto-lock.",
    problem: "Saat bekerja atau presentasi, pengguna sering kesulitan memindahkan file, menyinkronkan teks clipboard, atau mengontrol laptop Windows tanpa koneksi internet, cloud pihak ketiga yang lambat, atau kabel data yang merepotkan.",
    solution: "Lintas menghubungkan smartphone Android dan laptop Windows secara langsung melalui jaringan Wi-Fi lokal (Zero Cloud, Port 8945). Mengintegrasikan fungsi remote hardware laptop dan sinkronisasi data dengan latensi sangat rendah (<12ms) serta modul C++ Win32 API untuk eksekusi input tingkat rendah dan proteksi NearLock.",
    stats: [
      { label: "Arsitektur", val: "Local Client-Server (100% Offline)" },
      { label: "Port Jaringan", val: "Port 8945 (HTTP & WebSocket)" },
      { label: "Integritas Berkas", val: "SHA-256 Checksum Matching" },
      { label: "Latensi Kontrol", val: "< 12ms via WebSocket" },
    ],
    features: [
      {
        title: "Pairing Instan via QR Code",
        desc: "Menghubungkan HP dan PC dalam hitungan detik menggunakan token sesi kedaluwarsa otomatis.",
      },
      {
        title: "LAN Auto-Discovery",
        desc: "Deteksi otomatis perangkat di jaringan Wi-Fi yang sama tanpa perlu mengetik alamat IP manual.",
      },
      {
        title: "Remote Touchpad & Multi-Touch",
        desc: "Mengubah layar HP menjadi touchpad presisi tinggi dengan dukungan klik, scroll dua jari, dan drag-and-drop.",
      },
      {
        title: "Virtual Keyboard & Tombol Modifier",
        desc: "Mengetik ke laptop dari HP lengkap dengan tombol Ctrl, Alt, Shift, dan Windows Key.",
      },
      {
        title: "Instant Drop (Transfer File 2 Arah)",
        desc: "Mengirim file antar perangkat lewat Wi-Fi lokal berkecepatan tinggi dengan Drop Zone dan indikator kecepatan.",
      },
      {
        title: "Verifikasi Integritas SHA-256",
        desc: "Pengecekan hash file sebelum dan sesudah transfer untuk menjamin file tidak korup.",
      },
      {
        title: "Universal Clipboard",
        desc: "Salin teks di HP dan langsung tempel (paste) di Windows (dan sebaliknya) secara otomatis.",
      },
      {
        title: "NearLock (Smart Proximity)",
        desc: "Mengunci workstation Windows secara otomatis saat sinyal ponsel mendeteksi pengguna menjauhi laptop.",
      },
      {
        title: "Remote Presenter & Timer",
        desc: "Pengendali slide presentasi (Next/Previous, Black Screen) dilengkapi stopwatch pemantau durasi bicara.",
      },
      {
        title: "Integrasi Native Windows API (C++)",
        desc: "Menggunakan API Win32 (SendInput dan LockWorkStation) untuk eksekusi input tingkat rendah.",
      },
    ],
    techStack: ["Flutter", "Dart", "C++ (Win32 API)", "Riverpod", "GoRouter", "Local HTTP & WebSocket (Port 8945)", "SHA-256 Checksum", "QR Code", "File Picker"],
    impact: "Mengeliminasi ketergantungan internet/cloud publik untuk transfer file sensitif dan meningkatkan produktivitas serta keamanan workstation.",
    demoUrl: "",
    demoText: "Lihat Demo",
    demoIcon: "fa-arrow-up-right-from-square",
    repoUrl: "https://github.com/ANTARTICA1/lintas-flutter",
    repoText: "Lihat di GitHub",
  },
  {
    id: 4,
    title: "NenaCare",
    category: "Workplace Safety & AI",
    categoryType: "web",
    role: "Fullstack Web & AI Automation Engineer",
    type: "AI K3 Incident Reporting & Monitoring System",
    status: "Production Showcase (2024)",
    period: "2024",
    image: "assets/nenacare.svg",
    description: "Sistem pelaporan dan pemantauan keselamatan kerja (K3) cerdas bertenaga Google Gemini AI dengan mode anonim, notifikasi Telegram dua arah, dan ekspor audit PDF.",
    problem: "Di lingkungan kafe dan F&B yang sibuk, potensi bahaya keselamatan kerja (kebocoran gas, kompor, kabel listrik terkelupas, lantai licin) kerap lambat dilaporkan. Karyawan atau pelanggan sering enggan melapor karena takut disalahkan, sementara manajemen kesulitan memilah prioritas tindakan cepat.",
    solution: "NenaCare mendigitalkan penanganan K3 secara menyeluruh: formulir pelaporan dengan opsi 100% Anonim untuk keamanan psikologis pelapor, evaluasi kronologi insiden via Google Gemini 2.5 Flash-Lite (JSON structured output) untuk scoring risiko dan checklist mitigasi darurat, peringatan instan ke Telegram Bot manajemen dengan inline button respons cepat, serta live dashboard Chart.js dan ekspor dokumen audit A4 via Dompdf.",
    stats: [
      { label: "AI Engine", val: "Google Gemini 2.5 Flash-Lite (JSON)" },
      { label: "Remote Action", val: "Telegram Bot Inline Keyboard" },
      { label: "Mode Laporan", val: "Pilihan Publik atau 100% Anonim" },
      { label: "Audit & Laporan", val: "Ekspor PDF Landscape & Chart.js" },
    ],
    features: [
      {
        title: "Formulir Pelaporan Multi-Kategori",
        desc: "Mencakup bahaya Api & Gas, Kelistrikan, Lingkungan & Kebersihan, serta Ergonomi & APD.",
      },
      {
        title: "Mode Laporan 100% Anonim",
        desc: "Menghapus identitas nama pelapor di database untuk menjamin keamanan psikologis pelapor.",
      },
      {
        title: "Analisis Otomatis AI Gemini",
        desc: "Membaca kronologi dan menghasilkan ringkasan insiden, estimasi dampak, dan checklist mitigasi darurat.",
      },
      {
        title: "Live Monitoring Feed",
        desc: "Kartu insiden real-time dengan badge status dan lencana urgensi prioritas AI.",
      },
      {
        title: "Alur Kerja Terstandarisasi",
        desc: "Tahapan status laporan yang jelas: Menunggu → Diproses → Selesai.",
      },
      {
        title: "Telegram Bot Dua Arah",
        desc: "Peringatan instan ke HP manajer kafe yang dapat langsung mengubah status insiden dari chat Telegram.",
      },
      {
        title: "Pusat Analitik Chart.js",
        desc: "Grafik distribusi kategori insiden dan status penyelesaian untuk evaluasi bulanan.",
      },
      {
        title: "Ekspor Laporan Audit PDF",
        desc: "Cetak dokumen audit K3 resmi siap tanda tangan berformat A4 landscape via Dompdf.",
      },
      {
        title: "Role-Based Access Control",
        desc: "Pemisahan hak akses antara staf admin kafe dan manajer operasional.",
      },
    ],
    techStack: ["PHP (OOP)", "MySQL", "Google Gemini 2.5 Flash-Lite API", "Telegram Bot API", "Chart.js", "Dompdf", "JavaScript", "Bootstrap Icons", "Composer"],
    impact: "Mempercepat penanganan insiden darurat K3 hingga di bawah 5 menit dan menyediakan arsip audit K3 formal yang akuntabel.",
    demoUrl: "",
    demoText: "Lihat Demo",
    demoIcon: "fa-arrow-up-right-from-square",
    repoUrl: "https://github.com/ANTARTICA1/NenaCare",
    repoText: "Lihat di GitHub",
  },
  {
    id: 5,
    title: "ITB STIKOM Bali TheoTown",
    category: "Game Modding & Simulation",
    categoryType: "tools",
    role: "Pixel Artist & Simulation Systems Modder",
    type: "Educational Simulation Mod & 2.5D Isometric Art",
    status: "Game Plugin Showcase (2024)",
    period: "2024",
    image: "assets/project3.webp",
    description: "Plugin simulasi edukasi resmi kampus ITB STIKOM Bali untuk game simulator kota TheoTown dengan aset pixel art isometrik 2.5D khas arsitektur Bali.",
    problem: "Dalam game simulasi kota TheoTown, katalog fasilitas pendidikan tinggi default sangat minim dan bergaya barat generik. Modder lain sering kali hanya membuat bangunan bertipe dekorasi pasif tanpa andil dalam mekanik simulasi game.",
    solution: "Plugin resmi kampus ITB STIKOM Bali Renon yang menggabungkan estetika seni piksel khas arsitektur Bali dengan fungsionalitas simulasi pendidikan aktif: menggambar aset visual 2.5D isometrik dengan ornamen khas Bali (atap tumpang, ornamen kukul, candi bentar), dan mengonfigurasi engine simulasi pendidikan (type: education) untuk menampung 2.500 mahasiswa virtual.",
    stats: [
      { label: "Tapak Bangunan", val: "5 × 5 Tile Isometric" },
      { label: "Tipe Objek Engine", val: "type: education (Simulasi Aktif)" },
      { label: "Kapasitas Mahasiswa", val: "2.500 Mahasiswa Virtual" },
      { label: "Radius Pengaruh", val: "700 Tile (Cakupan Luas Kota)" },
    ],
    features: [
      {
        title: "Desain Pixel Art Isometrik Presisi",
        desc: "Grafis 2.5D yang proporsional dan tidak terdistorsi saat diputar atau di-zoom di dalam game.",
      },
      {
        title: "Karakteristik Arsitektur Tradisional Bali",
        desc: "Mengusung atap bertingkat, relief dinding bata Bali, dan candi bentar khas nusantara.",
      },
      {
        title: "Fungsi Edukasi Nyata",
        desc: "Berkontribusi langsung menurunkan angka putus sekolah dan menaikkan indeks literasi kota.",
      },
      {
        title: "Pengaruh Edukasi 700 Tile",
        desc: "Membantu meningkatkan nilai tanah (land value) dan kepuasan warga di sekitar kampus.",
      },
      {
        title: "Konfigurasi Mesin via code.json",
        desc: "Pengaturan ID unik, lot size, frame grafis, dan bobot statistik yang terstandarisasi.",
      },
      {
        title: "Metadata plugin.manifest",
        desc: "Terverifikasi di Plugin Manager internal game dengan Author 'Gekaaaaa'.",
      },
      {
        title: "Dukungan Multiplatform",
        desc: "Kompatibel dipasang di ponsel Android maupun PC Windows/Steam.",
      },
      {
        title: "Dokumentasi Bilingual (ID/EN)",
        desc: "Panduan instalasi dan deskripsi dalam Bahasa Indonesia dan Bahasa Inggris untuk komunitas modding global.",
      },
    ],
    techStack: ["TheoTown Plugin API", "JSON (code.json)", "plugin.manifest", "Pixel Art Graphics (2.5D Isometric)", "Android & PC Cross-Platform"],
    impact: "Memperkenalkan arsitektur kampus lokal ke komunitas modding global TheoTown dengan fungsionalitas mekanik game pendidikan aktif.",
    demoUrl: "",
    demoText: "Lihat Demo",
    demoIcon: "fa-arrow-up-right-from-square",
    repoUrl: "https://github.com/ANTARTICA1/PLUGIN-STIKOM-BALI-THEOTOWN",
    repoText: "Lihat di GitHub",
  },
  {
    id: 6,
    title: "NeuroFly",
    category: "Computational Neuroscience",
    categoryType: "tools",
    role: "Neural Systems & Computational Bio Researcher",
    type: "Biological Connectome Pong AI Controller",
    status: "Research & Experimental Showcase (2024)",
    period: "2024",
    image: "assets/neurofly.svg",
    description: "Eksperimen komputasi neurosains yang memanfaatkan sirkuit saraf visual biologis lalat buah (Janelia MaleCNS v1.0) untuk mengendalikan permainan Pong.",
    problem: "Model AI modern membutuhkan pemrosesan tensor matriks yang berat dan daya listrik besar hanya untuk mendeteksi gerak dan navigasi sederhana. Sebaliknya, lalat buah (Drosophila melanogaster) bermanuver lincah dalam milidetik dengan konsumsi energi hanya beberapa mikrowatt.",
    solution: "NeuroFly merekonstruksi data nyata sirkuit saraf visual biologis lalat buah dari dataset mikroskop elektron konektom Janelia Research Campus (MaleCNS v1.0) untuk mengendalikan paddle pada permainan klasik Pong secara mandiri tanpa memerlukan pelatihan artificial neural network yang berat.",
    stats: [
      { label: "Dataset Referensi", val: "Janelia MaleCNS v1.0" },
      { label: "Neuron Teridentifikasi", val: "438 Neuron Visual Lobe" },
      { label: "Koneksi Sinaptik", val: "2.199 Koneksi Terarah" },
      { label: "Total Kontak", val: "12.282 Hubungan Sinapsis" },
    ],
    features: [
      {
        title: "Konektom Biologis Riil",
        desc: "Rekonstruksi struktur saraf nyata dari visual lobe lalat buah berbasis neuPrint API.",
      },
      {
        title: "Model Elementary Motion Detector (EMD)",
        desc: "Penerapan sirkuit komputasi Hassenstein-Reichardt correlator berbasis neuron T4 (on-motion) dan T5 (off-motion).",
      },
      {
        title: "Pelacakan Target Sel LC11",
        desc: "Memanfaatkan respons sel Lobula Columna 11 yang terspesialisasi mengenali objek kecil bergerak (bola Pong).",
      },
      {
        title: "Transduksi Sinyal Motorik Real-Time",
        desc: "Mengubah beda potensial aksi sinapsis biologis menjadi pergerakan paddle Pong atas dan bawah.",
      },
      {
        title: "Visualisasi Topologi Jaringan",
        desc: "Menampilkan graf aliran sinyal antar neuron visual secara interaktif dengan NetworkX.",
      },
    ],
    techStack: ["Python", "neuPrint API", "Janelia MaleCNS v1.0", "NumPy", "NetworkX", "HTML5 Canvas"],
    impact: "Membuktikan efisiensi arsitektur jaringan saraf biologis mikroskopis untuk otomasi kendali visual tanpa komputasi GPU berdaya tinggi.",
    demoUrl: "",
    demoText: "Lihat Demo",
    demoIcon: "fa-arrow-up-right-from-square",
    repoUrl: "https://github.com/ANTARTICA1",
    repoText: "Lihat di GitHub",
  },
  {
    id: 7,
    title: "Bingkai",
    category: "Desktop & Local-First Utility",
    categoryType: "tools",
    role: "Backend & Local-First Systems Developer",
    type: "Local Photo Curation & Gamepad Media Server",
    status: "Production Prototype (2024)",
    period: "2024",
    image: "assets/bingkai.svg",
    description: "Aplikasi kurasi dan galeri foto lokal 100% offline (Zero Cloud) dengan mode kurasi Tinder-Style, pendeteksi foto kembar, dan kontrol via stik gamepad / remote HP.",
    problem: "Folder foto di laptop sering kali berisi ribuan foto tak beraturan dan banyak duplikat. Merapikannya menggunakan mouse terasa kaku dan membosankan, sementara mengunggahnya ke cloud publik memicu kekhawatiran privasi data dan memakan kuota internet.",
    solution: "Bingkai bekerja 100% Offline & Local-First. Foto tidak dipindahkan, tidak digandakan, dan tidak diunggah ke internet. Bingkai membaca folder lokal dan menyajikannya dalam galeri super cepat yang bisa dikontrol dari sofa sambil rebahan menggunakan stik controller atau smartphone via Wi-Fi lokal.",
    stats: [
      { label: "Privasi Mutlak", val: "100% Offline (Zero Cloud)" },
      { label: "Kontrol Fleksibel", val: "Stik Gamepad & Remote Wi-Fi HP" },
      { label: "Metode Kurasi", val: "Tinder-Style Swipe Review" },
      { label: "Efisiensi Harddisk", val: "Pendeteksi Foto Kembar Identik" },
    ],
    features: [
      {
        title: "Rebahan Mode (Gamepad & Remote HP)",
        desc: "Kontrol galeri di layar monitor PC dari jarak jauh menggunakan stick controller atau browser smartphone via Wi-Fi lokal.",
      },
      {
        title: "Tinder-Style Swipe Review",
        desc: "Geser kanan / tekan tombol gamepad untuk menyimpan foto ke favorit, geser kiri untuk membuang foto yang blur/gagal.",
      },
      {
        title: "Pendeteksi Foto Kembar (Duplicate Finder)",
        desc: "Algoritma pencocokan foto untuk menemukan foto identik yang memakan ruang harddisk.",
      },
      {
        title: "Album Virtual",
        desc: "Mengelompokkan foto ke dalam album tematik tanpa perlu memindahkan atau menggandakan file aslinya di folder.",
      },
      {
        title: "Tong Sampah Anti-Panik (Safe Trash)",
        desc: "Foto yang dibuang ditampung sementara di tempat sampah aplikasi dan dapat di-restore kapan saja ke folder aslinya.",
      },
      {
        title: "Pemindaian Kilat (Pillow-WebP Caching)",
        desc: "Pembuatan thumbnail ringan berformat WebP agar ribuan foto termuat mulus tanpa lag.",
      },
    ],
    techStack: ["Python", "FastAPI", "SQLite", "Alpine.js", "Tailwind CSS", "Pillow-WebP", "HTML5 Gamepad API", "Local Wi-Fi Remote"],
    impact: "Menghemat ruang penyimpanan lokal dan memangkas waktu pengorganisasian ribuan foto keluarga tanpa risiko kebocoran privasi cloud.",
    demoUrl: "",
    demoText: "Lihat Demo",
    demoIcon: "fa-arrow-up-right-from-square",
    repoUrl: "https://github.com/ANTARTICA1/bingkai-app",
    repoText: "Lihat di GitHub",
  },
  {
    id: 8,
    title: "Makalah Generator",
    category: "Generative AI & Academic",
    categoryType: "web",
    role: "Fullstack AI & Academic Tools Developer",
    type: "Generative AI Academic Research & Paper Assistant",
    status: "Portfolio Project Showcase (2024)",
    period: "2024",
    image: "assets/makalah-generator.svg",
    description: "Asisten penelitian dan generator draf karya ilmiah cerdas bertenaga OpenAI GPT-4 yang menyusun hipotesis, sitasi otomatis (APA/IEEE), dan ekspor LaTeX/PDF.",
    problem: "Penyusunan kerangka awal draf penelitian, perumusan hipotesis akademik, dan pemformatan sitasi daftar pustaka sering kali menyita waktu berhari-hari bagi mahasiswa dan peneliti.",
    solution: "Mengembangkan web app modern berbasis Next.js 14 App Router yang mengorkestrasi pipeline prompt AI akademis terstruktur untuk merumuskan rumusan masalah ilmiah, menyusun sitasi standar internasional (APA 7th, IEEE, Harvard), dan mengompilasi draf langsung ke dokumen PDF siap pakai atau kode sumber LaTeX.",
    stats: [
      { label: "Waktu Generasi AI", val: "AI Academic Pipeline < 45 Detik" },
      { label: "Standar Sitasi", val: "APA 7th Edition, IEEE, & Harvard" },
      { label: "Output Engine", val: "LaTeX Source Code & Kompilasi PDF" },
      { label: "Frontend Stack", val: "Next.js 14 Server Actions & TypeScript" },
    ],
    features: [
      {
        title: "AI Academic Pipeline (<45 Detik)",
        desc: "Membantu merumuskan latar belakang masalah, rumusan masalah, dan hipotesis penelitian secara ilmiah dan terstruktur.",
      },
      {
        title: "Format Sitasi Otomatis",
        desc: "Menata daftar referensi sitasi sesuai standar sitasi akademik resmi seperti APA edisi ke-7, IEEE, dan Harvard.",
      },
      {
        title: "Ekspor Multi-Format (PDF & LaTeX)",
        desc: "Mengunduh draf dalam format PDF siap baca atau kode sumber dokumen LaTeX siap kompilasi.",
      },
      {
        title: "Penyunting Kerangka Draf Interaktif",
        desc: "Editor teks terstruktur untuk menyempurnakan setiap bab (Pendahuluan, Metodologi, Tinjauan Pustaka).",
      },
      {
        title: "Validasi Konsistensi Argumen",
        desc: "Evaluasi koherensi antara rumusan masalah, hipotesis penelitian, dan kesimpulan yang dihasilkan.",
      },
    ],
    techStack: ["Next.js 14", "TypeScript", "Tailwind CSS", "OpenAI GPT-4 API", "LaTeX Engine", "PDF Export"],
    impact: "Mengakselerasi penyusunan draf awal penelitian hingga 80% lebih cepat tanpa mengorbankan kaidah dan standar sitasi ilmiah.",
    demoUrl: "",
    demoText: "Lihat Demo",
    demoIcon: "fa-arrow-up-right-from-square",
    repoUrl: "https://github.com/ANTARTICA1",
    repoText: "Lihat di GitHub",
  },
];

// Ekspos ke window untuk interoperabilitas antar-modul
if (typeof window !== "undefined") {
  window.projectsData = projectsData;
}
